teams:
  - name: "Team A"
    context: ""
  - name: "Team B"
    context: ""
  - name: "Team C"
    context: ""
  - name: "Team D"
    context: ""
  

api:
  openai:
    base_url: "https://api.openai.com/v1"
    model: "dall-e-3"
    size: "1024x1024"
    quality: "standard"
    n: 1
    api_key: "api_key_here"
